### ISSUE TITLE
Website Fixes

### ISSUE THREAD

**Issue by geodawg** [DigitalGlobe/DeepCore#15]
All,

We need to correct some minor issues with the website. 

1. We need to link back to the GitHub Issues page from the main site. Please a several links to the GitHub issues page at the top and the bottom of the page.
2. Please add an "Architecture" link somewhere on the homepage. This can easily go under the navigation menu.
3. Please add a link to the GitHub main page in the top left-hand corner of the website.
4. Add the Blog

**Comment by geovations** [comment]
1.  There are now Issues links at the top and bottom of each page
3.  The github image at the top of the page links back to Github.com

**Comment by geovations** [comment]
Issue 2.   The Pages link now has a link to the Architecture page
