### ISSUE TITLE
Blog hyperlink pointing relative to post vs. root

### ISSUE THREAD

**Issue by mrabenhorst** [DigitalGlobe/DeepCore#24]
Page links are not working properly from blog post. Try: 

1. Home -> 
2. Blog -> 
3. Alan's post -> 
4. Click "Home" on the bar. 

You get a 404 from here: https://digitalglobe.github.io/DeepCore/2017/04/11/index.html

**Comment by geovations** [comment]
Fixed.  The Home link was not using the liquid syntax everything else was.
